### ISSUE TITLE
화면 역할 분담

### ISSUE THREAD

**Issue by bellKong** [team-cwf/yeohanglog-android#2]
## 개요
UI팀 개인 각 xml 분담

## 화면 구성
> `완료` : :o:
> `진행중` : :wrench:

|진행|구분|XML|담당자|issue|
|:---:|:---|:---|:---:|:---:|
|:o:|스플래시                 |activity_splash                 |`김현아`||
|:o:|로그인                    |activity_sign_in                |`김보민`||
|    |메인                       |activity_main                    |`김민재`||
|    |메인 - 홈                |fragment_main_home     |`김민재`||
|:o:|메인 - 여행록          |fragment_main_trip         |`김민재`||
|:o:|메인 - 여행록 - 여행|fragment_main_trip_plan|`김민재`||
|    |메인 - 여행록 - 기록|fragment_main_trip_log  |`김보민`|#35|
|:o:|메인 - 더보기          |fragment_main_more      |`김민재`||
|    |여행 - 등록             |activity_trip_info               |`김보민`||
|    |여행 - 등록 - 이름   |                                          |`김보민`||
|    |여행 - 등록 - 기간   |                                          |`김보민`||
|    |여행 - 계획             |activity_trip_plan              |`김민재`|#40|
|:o:|여행 - 계획 - 가계부|activity_trip_account        |`김보민`|#34|
|:o:|여행 - 계획 - 준비물|activity_trip_check           |`김보민`||
|:o:|여행 - 계획 - 일행   |activity_trip_member       |`김현아`||
|    |여행 - 계획 - 사진   |activity_trip_album           |`김현아`|#39|
|    |기록                       |                                          |`김현아`||
||~~메인 - 검색~~             |~~fragment_main_search~~    ||-|

## 참고사항
- [ ] 기록 관련 화면 구성 @bellKong 정의 필요
- 검색 화면은 기획단계에서 현재 상태로 마무리 처리

**Comment by Man-jae** [comment]
할당 및 진행사항 업데이트 했습니다.
