### ISSUE TITLE
이왕 이렇게 된거 TDD 를 위한 테스트 코드 작성 안내

### ISSUE THREAD

**Issue by Man-jae** [team-cwf/yeohanglog-android#59]
## 개요
- 테스트 코드를 공부도 하고 생활화 해보고 싶어서 참고가 될만한 사이트 공유합니다.
- 보이는대로 공유하고, 공부좀 되면 정리하도록 하겠습니다.

## 참고
- [뱅크샐러드 - 테스트 코드, 안드로이드에서는 어떻게 작성해야 할까?](https://blog.banksalad.com/tech/test-in-banksalad-android/)
- [미디엄 - 설마 아직도 테스트 코드를 작성 안하시나요?](https://medium.com/@ssowonny/%EC%84%A4%EB%A7%88-%EC%95%84%EC%A7%81%EB%8F%84-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C%EB%A5%BC-%EC%9E%91%EC%84%B1-%EC%95%88-%ED%95%98%EC%8B%9C%EB%82%98%EC%9A%94-b54ec61ef91a)
- [우아한형제들 - 테스트 코드 없이 레거시 코드를 다 감수하시겠습니까?](https://woowabros.github.io/experience/2019/02/27/Working_Effectively_with_Legacy_Code.html)

**Comment by bellKong** [comment]
공유 감사드립니다
